---

- name: Install Required packages
  shell: yum install -y policycoreutils-python
  tags:
    - selinux_policies

- name: Security context of passenger registry directory
  shell: semanage fcontext -a -t var_run_t /var/lib/passenger-instreg
  tags:
    - passenger_install
    - selinux_policies

- name: Security context for tmp/ rails directory
  shell: semanage fcontext -a -t httpd_sys_rw_content_t "{{ application_path}}access/tmp"
  tags:
    - create_rails_directories
    - selinux_policies

- name: Create a policy to assign the httpd_log_t context to the logging directories
  shell: semanage fcontext -a -t httpd_log_t "{{ application_path }}acccess/log(/.*)?"
  tags:
    - selinux_policies

- name: Create a policy to assign the httpd_cache_t context to our cache directories.
  shell: semanage fcontext -a -t httpd_cache_t "{{ application_path }}access/tmp/cache(/.*)?"
  tags:
    - selinux_policies

- name: Applying the SELinux Policy
  shell: restorecon -Rv {{ application_path }}access
  tags:
    - selinux_policies
