---

- name: Creates folder tmp
  file: path={{ application_path }}access/tmp state=directory
  tags:
    - Creating_SELinux_Policies

- name: Creates folder cache
  file: path={{ application_path }}access/tmp/cache state=directory
  tags:
    - Creating_SELinux_Policies

- name: Creates folder log
  file: path={{ application_path }}access/log state=directory
  tags:
    - Creating_SELinux_Policies

- name: Creates file development.log
  file: path={{ application_path }}access/log/development.log state=touch
  tags:
    - Creating_SELinux_Policies

- name: Install Required packages
  shell: yum install -y policycoreutils-python
  tags:
    - Creating_SELinux_Policies

- name: Changing folder permissions
  shell: chown {{application_user}}:{{application_user}} {{ application_path }}access/tmp ; chown {{application_user}}:{{application_user}} {{ application_path }}access/tmp/cache ;chmod 775 {{ application_path }}access/tmp
  tags:
    - Creating_SELinux_Policies

- name: Changing file permissions
  shell: chown {{application_user}}:{{application_user}} {{ application_path }}access/log ; chown {{application_user}}:{{application_user}} {{ application_path }}access/log/development.log ;chmod 0644 {{ application_path }}access/log/development.log
  tags:
    - Creating_SELinux_Policies



- name: Create a policy to assign the httpd_log_t context to the logging directories
  shell: semanage fcontext -a -t httpd_log_t "{{ application_path }}acccess/log(/.*)?"
  tags:
    - Creating_SELinux_Policies

- name: Create a policy to assign the httpd_cache_t context to our cache directories.
  shell: semanage fcontext -a -t httpd_cache_t "{{ application_path }}access/tmp/cache(/.*)?"
  tags:
    - Creating_SELinux_Policies

- name: Changing the context for the root html directories
  shell: semanage fcontext -a -t httpd_sys_rw_content_t "{{ application_path }}access(/.*)?"
  tags:
    - Creating_SELinux_Policies

- name: Applying the SELinux Policy
  shell: restorecon -Rv {{ application_path }}access
  tags:
    - Creating_SELinux_Policies

- name: Generate new SELinux policy module
  shell: setenforce 0
  tags:
    - Creating_SELinux_Policies

- name: Generate new SELinux policy module
  shell: service httpd restart
  tags:
    - Creating_SELinux_Policies

- name: Generate new SELinux policy module
  shell: grep httpd /var/log/audit/audit.log | audit2allow -M passenger
  tags:
    - Creating_SELinux_Policies

- name: Generate new SELinux policy module
  shell: semodule -i passenger.pp
  tags:
    - Creating_SELinux_Policies

- name: Generate new SELinux policy module
  shell: setenforce 1
  tags:
    - Creating_SELinux_Policies



- name: migrate
  shell: bash -lc "rake db:migrate" chdir="{{ application_path }}/access"
  tags:
    - Creating_SELinux_Policies

- name: Changing bd owner
  shell: chown {{application_user}}:{{application_user}} {{ application_path }}access/db ; chown {{application_user}}:{{application_user}} {{ application_path }}access/db/development.sqlite3
  tags:
    - Creating_SELinux_Policies

- name: Restarting httpd service
  shell: service httpd restart
  tags:
    - Creating_SELinux_Policies
